/*
 * Copyright (c) 2015 Motorola Mobility, LLC.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <stdlib.h>
#include <stdio.h>

#include <nuttx/arch.h>
#include <arch/tsb/cdsi.h>

#include "chip.h"
#include "up_arch.h"
#include "tsb_scm.h"

#include <arch/tsb/cdsi_reg_def.h>

//#define CONFIG_CDSI_DBG_VERBOSE
#if defined(CONFIG_CDSI_DBG_VERBOSE)
#define CDSI_DBG_REG(x) { x, #x }
#else
#define CDSI_DBG_REG(x) { x, 0 }
#endif

struct dbg_entry {
    uint32_t val;
    const char *const str;
};

static void cdsi_dump_register_array(uint32_t base, const struct dbg_entry *registers, size_t entries) {
    while (entries) {
        printf("%08x %s: %08x\n", base+registers->val, (registers->str ? registers->str : ""), getreg32(base + registers->val));
        registers++;
        entries--;
    }
}

const static struct dbg_entry CDSI_REGISTERS[] = {
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_FUNC_ENABLE_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_FUNC_ENABLE_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_FUNC_ENABLE_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_FUNC_ENABLE_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_DPHY_RESET_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_PLL_CONFIG_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_PLL_CONFIG_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_PLL_CONFIG_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_PLL_CONTROL_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_PLL_CONTROL_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_LANE_ENABLE_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_LANE_ENABLE_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_LANE_ENABLE_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_VREG_CONFIG_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_VREG_CONTROL_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_LPRX_CALIB_CONFIG_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_LPRX_CALIB_CONTROL_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_CSI2DSI_SELECT_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_04_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_05_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_06_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_07_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_08_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_09_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_GLOBAL_TIMING_PARAM_10_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_04_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_05_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_06_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_07_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_08_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_09_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_10_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_COUNT_CONFIG_11_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_04_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_05_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_06_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_07_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_08_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_09_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_10_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_11_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_12_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_13_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_14_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONFIG_15_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_INIT_CONTROL_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_INIT_CONTROL_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_INIT_CONTROL_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_INIT_CONTROL_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_LINK_RESET_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_APF_RESET_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_INIT_CONTROL_04_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_STATUS_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_STATUS_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_STATUS_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_STATUS_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_STATUS_04_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_STATUS_05_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_STATUS_06_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_MASK_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_MASK_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_MASK_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_MASK_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_MASK_04_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_MASK_05_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_INTERRUPT_MASK_06_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_LPRXIF_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_LPRXIF_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_LPRXIF_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_LPRXIF_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_LPRXIF_04_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CMDIF_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CMDIF_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CMDIF_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CMDIF_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_CONTROL_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_DBG_CONFIG_00_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_DBG_CONFIG_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_STATUS_01_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_STATUS_02_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_STATUS_03_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_STATUS_04_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_STATUS_05_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_STATUS_06_OFFS),
    CDSI_DBG_REG(CDSI_CDSITX_SIDEBAND_STATUS_07_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_MODE_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_WAIT_CYCLE_SET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_VSYNC_LINE_SET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_TYPE_SEL1_SET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_TYPE_SEL2_SET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_TYPE_MASK1_SET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_TYPE_MASK2_SET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_COM_START_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_COM_SET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_COM_VDELAYSTRCOUNT_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_COM_VDELAYENDCOUNT_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_COM_MAXFCNT_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_COM_3DCM_PLDT_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_COM_3DCM_LINE_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_SYN_SET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_SYN_LINE_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_VPARAM_UPDATE_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_PIC_COM_STATUS_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_STATUS_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_STATUS_ENABLE_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_CDSITX_MODE_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_UNIPRO_BYTESWAP_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_SOFT_RESET_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_SYSCLK_ENABLE_OFFS),
    CDSI_DBG_REG(CDSI_AL_TX_BRG_ENABLE_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_ADDRESS_CONFIG_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CLKEN_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CLKSEL_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_MODE_CONFIG_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_SYSTEM_INIT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_LANE_ENABLE_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_VC_ENABLE_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_START_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_LINE_INIT_COUNT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_HSRXTO_COUNT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_FUNC_ENABLE_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTX_MODE_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_TATO_COUNT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTXTO_COUNT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_WAITBTA_COUNT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_FUNC_MODE_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_LPRX_STATE_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_LPRX_STATE_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_RXTRIG_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_RXTRIG_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_INTERNAL_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_RXERR_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_RXERR_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_TXERR_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_TXERR_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_ERR_STATUS_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTX_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTX_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTX_REQ_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTX_TYPE_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTX_PKT_HDR_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTX_PAYLOAD0_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_LPTX_PAYLOAD1_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_HSRX_CNTRL_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_HSRX_COUNT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_DPHY_DLYCNTRL_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_DPHY_LPRX_THSLD_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_DPHY_LPRXCALCNTRL_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_DPHY_LPRXAUTOCALST_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_DPHY_MON_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_DPHY_LPTXTIMECNT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_DSI_BTA_COUNT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_PPI_DSI_DPHYTX_ADJUST_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_LANE_STATUS_HS_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_LANE_STATUS_LP_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC0_SH_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC0_SH_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC1_SH_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC1_SH_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC2_SH_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC2_SH_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC3_SH_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC3_SH_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC0_LN_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC0_LN_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC1_LN_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC1_LN_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC2_LN_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC2_LN_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC3_LN_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_DSI_VC3_LN_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC0_SH_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC0_SH_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC1_SH_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC1_SH_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC2_SH_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC2_SH_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC3_SH_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC3_SH_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC0_LN0_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC0_LN1_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC0_LN0_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC0_LN1_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC1_LN0_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC1_LN1_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC1_LN0_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC1_LN1_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC2_LN0_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC2_LN1_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC2_LN0_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC2_LN1_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC3_LN0_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC3_LN1_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC3_LN0_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC3_LN1_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_RCV_PKT_HEADER_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC0_FNLN_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC1_FNLN_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC2_FNLN_STAT_OFFS),
    CDSI_DBG_REG(CDSI_CDSIRX_CSI2_VC3_FNLN_STAT_OFFS),
    CDSI_DBG_REG(CDSI_AL_RX_BRG_MODE_OFFS),
    CDSI_DBG_REG(CDSI_AL_RX_BRG_INT_STAT_OFFS),
    CDSI_DBG_REG(CDSI_AL_RX_BRG_INT_MASK_OFFS),
    CDSI_DBG_REG(CDSI_AL_RX_BRG_CSI_INFO_OFFS),
    CDSI_DBG_REG(CDSI_AL_RX_BRG_CSI_DT0_OFFS),
    CDSI_DBG_REG(CDSI_AL_RX_BRG_CSI_DT1_OFFS),
    CDSI_DBG_REG(CDSI_AL_RX_BRG_CSI_DT2_OFFS),
    CDSI_DBG_REG(CDSI_AL_RX_BRG_CSI_DT3_OFFS),
};

void cdsi0_dump(void) {
    cdsi_dump_register_array(CDSI0_REG_BASE, CDSI_REGISTERS, sizeof(CDSI_REGISTERS)/sizeof(CDSI_REGISTERS[0]));
}

void cdsi1_dump(void) {
    cdsi_dump_register_array(CDSI1_REG_BASE, CDSI_REGISTERS, sizeof(CDSI_REGISTERS)/sizeof(CDSI_REGISTERS[0]));
}

